on: [push, pull_request]
name: |
  CI
  abc
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        racket-version: ["current"]
        racket-variant: ["CS"]
        include:
          - racket-version: current
            experimental: true
    steps:
      - uses: actions/checkout@v2
      - uses: Bogdanp/setup-racket@v1.7
        with:
          architecture: x64
          distribution: minimal
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Installing test and its dependencies
        run: racket -e '(println 1)'
